name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Archive artifacts
        run: |
          mkdir -p build
          mkdir -p build-dll
          copy target\release\dir-summary* build\
          copy target\release\dirSummary* build-dll\ 
          powershell Compress-Archive -Path build\* -DestinationPath build\artifacts.zip
          powershell Compress-Archive -Path build-dll\* -DestinationPath build-dll\dll-artifacts.zip
      - name: List build directory
        run: |
          dir build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            build\artifacts.zip
            build-dll\dll-artifacts.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifacts

      - name: List Downloaded Files
        run: |
          ls -R

      - name: Get Current Date
        id: get_date
        run: |
          TAG_NAME=$(date "+%Y.%m.%d.%H.%M.%S")
          echo "New tag name will be: $TAG_NAME"
          run: echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: $TAG_NAME
          files: |
            ./build/artifacts.zip
            ./build-dll/dll-artifacts.zip

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
